resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: Github
      path: vivektrivedi-123/4sight
      branches:
        include: dev
  - name: myBuildInfo
    type: BuildInfo
    configuration:
pipelines:  
  - name: basic_pipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
          outputResources:
            - name: myBuildInfo             
        execution:
          onExecute:
            - npm i
            - npm run build